# Generated by Django 5.2.1 on 2025-05-10 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_hours_per_day', models.FloatField()),
                ('social_media_hours', models.FloatField()),
                ('netflix_hours', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('mental_health_rating', models.IntegerField()),
                ('attendance_percentage', models.FloatField()),
                ('part_time_job', models.BooleanField()),
                ('extracurricular_participation', models.BooleanField()),
                ('result', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
